services:
  devcontainer:
    image: openiap/devcontainer:latest
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    working_dir: /src
    volumes:
       - ..:/src
       - "/var/run/docker.sock:/var/run/docker.sock"
    command: sleep infinity
  rabbitmq:
    image: "rabbitmq:3-management"
    restart: always
  mongodb:
    image: "mongo"
    restart: always
    # volumes:
    #   - mongodb_data:/data/db
